-- CRM login schema for Oracle Database 21c
-- Quoted identifiers match JPA @Table names ("users", "groups", "user_groups").
-- Oracle 21c: BOOLEAN is not available; use NUMBER(1) for flags (Hibernate maps booleans the same way).
-- Date/time columns use TIMESTAMP(6) without time zone; values are stored as UTC wall time (app uses LocalDateTime UTC).

CREATE TABLE "groups" (
    group_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name        VARCHAR2(100) NOT NULL UNIQUE,
    created_by        VARCHAR2(100) NOT NULL,
    created_date      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_updated_by   VARCHAR2(100) NOT NULL,
    last_updated_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    oca_control       NUMBER(19) DEFAULT 0 NOT NULL
);

CREATE TABLE "users" (
    user_id                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name                     VARCHAR2(100) NOT NULL UNIQUE,
    first_name                    VARCHAR2(100) NOT NULL,
    last_name                     VARCHAR2(100) NOT NULL,
    password_hash                 VARCHAR2(255) NOT NULL,
    password_salt                 VARCHAR2(255) DEFAULT '' NOT NULL,
    email                         VARCHAR2(255) NOT NULL UNIQUE,
    phone_number                  VARCHAR2(50),
    login_attempts                NUMBER(10) DEFAULT 0 NOT NULL,
    user_status                   VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    temporary_password_hash       VARCHAR2(255),
    temporary_password_expires_at   TIMESTAMP(6),
    must_change_password          NUMBER(1) DEFAULT 0 NOT NULL
        CONSTRAINT chk_users_must_chg CHECK (must_change_password IN (0, 1)),
    created_by                    VARCHAR2(100) NOT NULL,
    created_date                  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_updated_by               VARCHAR2(100) NOT NULL,
    last_updated_date             TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    oca_control                   NUMBER(19) DEFAULT 0 NOT NULL
);

CREATE TABLE "user_groups" (
    user_id           NUMBER(19) NOT NULL,
    group_id          NUMBER(19) NOT NULL,
    created_by        VARCHAR2(100) NOT NULL,
    created_date      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_updated_by   VARCHAR2(100) NOT NULL,
    last_updated_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    oca_control       NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_user_groups PRIMARY KEY (user_id, group_id),
    CONSTRAINT fk_ug_user FOREIGN KEY (user_id) REFERENCES "users" (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_ug_group FOREIGN KEY (group_id) REFERENCES "groups" (group_id) ON DELETE CASCADE
);

CREATE INDEX idx_users_email ON "users" (email);
CREATE INDEX idx_users_user_name ON "users" (user_name);
